"""fix seats relations and movie property

Revision ID: 0bc212c97efb
Revises: 4a173d6f8b7d
Create Date: 2026-04-29 16:10:02.602145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc212c97efb'
down_revision: Union[str, Sequence[str], None] = '4a173d6f8b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('movie', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'movie')
    # ### end Alembic commands ###
