"""create rooms and seats tables

Revision ID: 4a173d6f8b7d
Revises: 
Create Date: 2026-04-29 02:58:10.774743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a173d6f8b7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horizontal', sa.String(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_seat_horizontal'), table_name='seat')
    op.drop_index(op.f('ix_seat_is_available'), table_name='seat')
    op.drop_index(op.f('ix_seat_vertical'), table_name='seat')
    op.drop_table('seat')
    op.drop_index(op.f('ix_room_movie'), table_name='room')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_table('room')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('movie', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_index(op.f('ix_room_movie'), 'room', ['movie'], unique=False)
    op.create_table('seat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('horizontal', sa.VARCHAR(), nullable=False),
    sa.Column('vertical', sa.VARCHAR(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_vertical'), 'seat', ['vertical'], unique=False)
    op.create_index(op.f('ix_seat_is_available'), 'seat', ['is_available'], unique=False)
    op.create_index(op.f('ix_seat_horizontal'), 'seat', ['horizontal'], unique=False)
    op.drop_table('seats')
    op.drop_table('rooms')
    # ### end Alembic commands ###
