"""create seat to user relationship

Revision ID: c2cbe6024520
Revises: af1a1b5ab618
Create Date: 2026-05-01 21:20:58.901071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cbe6024520'
down_revision: Union[str, Sequence[str], None] = 'af1a1b5ab618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('horizontal', sa.VARCHAR(), nullable=False),
    sa.Column('vertical', sa.VARCHAR(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
